package com.travelapp.gaps.domain;

public enum GapType {
    NO_TRANSPORT_BETWEEN_DESTINATIONS,
    ARRIVAL_WITHOUT_ACCOMMODATION,
    DAYS_WITHOUT_ACCOMMODATION,
    TRANSPORT_ONLY_DRAFT,
    PENDING_PAYMENT_DEADLINE,
    CANCELLATION_DEADLINE_NEAR,
    TIGHT_CONNECTION,
    FREE_DAYS
}
